"""customer table

Revision ID: 32323a52f55a
Revises: 84d3877f0379
Create Date: 2026-08-25 10:46:41.852596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32323a52f55a'
down_revision: Union[str, None] = '84d3877f0379'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.add_column('appointments', sa.Column('reference_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_appointments_reference_code'), 'appointments', ['reference_code'], unique=True)
    op.add_column('chat_sessions', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_sessions_customer_id'), 'chat_sessions', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_customer_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'customer_id')
    op.drop_index(op.f('ix_appointments_reference_code'), table_name='appointments')
    op.drop_column('appointments', 'reference_code')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
