"""staff modal

Revision ID: 5266269807d3
Revises: e877e8567ad6
Create Date: 2026-09-10 16:20:42.881607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5266269807d3'
down_revision: Union[str, None] = 'e877e8567ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('category', sa.String(length=120), nullable=True))
    op.add_column('staff', sa.Column('specialty', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'specialty')
    op.drop_column('services', 'category')
    # ### end Alembic commands ###
