"""business doc

Revision ID: 5b541868256e
Revises: 62d8b09cd61e
Create Date: 2026-09-15 15:17:28.719295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b541868256e'
down_revision: Union[str, None] = '62d8b09cd61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_document_uploads',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('document_type', postgresql.ENUM('INVOICE', 'RECEIPT', 'PURCHASE_ORDER', 'RESUME', 'EXPENSE_REPORT', 'APPLICATION_FORM', 'CONTRACT', 'UNKNOWN', name='businessdocumenttype', create_type=False), nullable=False),
    sa.Column('type_confidence', sa.Float(), nullable=True),
    sa.Column('requested_document_type', sa.String(length=30), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'NEEDS_REVIEW', 'FAILED', name='businessdocumentstatus', create_type=False,), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('field_confidence', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_document_uploads_content_hash'), 'business_document_uploads', ['content_hash'], unique=False)
    op.create_index(op.f('ix_business_document_uploads_document_type'), 'business_document_uploads', ['document_type'], unique=False)
    op.create_index(op.f('ix_business_document_uploads_status'), 'business_document_uploads', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('type', sa.Enum('BUSINESS_DOCUMENT_COMPLETED', 'BUSINESS_DOCUMENT_NEEDS_REVIEW', 'BUSINESS_DOCUMENT_LOW_CONFIDENCE', 'BUSINESS_DOCUMENT_FAILED', 'KB_DOCUMENT_COMPLETED', 'KB_DOCUMENT_FAILED', 'APPOINTMENT_BOOKED', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_RESCHEDULED', 'GENERIC', name='notificationtype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', name='notificationseverity'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('related_id', sa.String(length=64), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_related_id'), 'notifications', ['related_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('application_forms',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('upload_id', sa.String(length=16), nullable=False),
    sa.Column('applicant_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('position_applied_for', sa.String(length=255), nullable=True),
    sa.Column('submission_date', sa.String(length=20), nullable=True),
    sa.Column('additional_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['business_document_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_table('contracts',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('upload_id', sa.String(length=16), nullable=False),
    sa.Column('contract_title', sa.String(length=255), nullable=True),
    sa.Column('contract_type', sa.String(length=120), nullable=True),
    sa.Column('party_a', sa.String(length=255), nullable=True),
    sa.Column('party_b', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.String(length=20), nullable=True),
    sa.Column('expiration_date', sa.String(length=20), nullable=True),
    sa.Column('contract_value', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('key_terms', sa.JSON(), nullable=True),
    sa.Column('governing_law', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['business_document_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_table('expense_reports',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('upload_id', sa.String(length=16), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=True),
    sa.Column('employee_id', sa.String(length=80), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('report_date', sa.String(length=20), nullable=True),
    sa.Column('expense_period_start', sa.String(length=20), nullable=True),
    sa.Column('expense_period_end', sa.String(length=20), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('approver_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['business_document_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('upload_id', sa.String(length=16), nullable=False),
    sa.Column('invoice_number', sa.String(length=120), nullable=True),
    sa.Column('invoice_date', sa.String(length=20), nullable=True),
    sa.Column('due_date', sa.String(length=20), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('vendor_address', sa.Text(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['business_document_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('upload_id', sa.String(length=16), nullable=False),
    sa.Column('po_number', sa.String(length=120), nullable=True),
    sa.Column('po_date', sa.String(length=20), nullable=True),
    sa.Column('vendor_name', sa.String(length=255), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=True),
    sa.Column('delivery_date', sa.String(length=20), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['business_document_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('upload_id', sa.String(length=16), nullable=False),
    sa.Column('receipt_number', sa.String(length=120), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('merchant_address', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.String(length=20), nullable=True),
    sa.Column('transaction_time', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('payment_method', sa.String(length=80), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['business_document_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('upload_id', sa.String(length=16), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['business_document_uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_id')
    )
    op.create_table('contract_signatories',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('contract_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_report_items',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('expense_report_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['expense_report_id'], ['expense_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_line_items',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('invoice_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_line_items',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('purchase_order_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipt_items',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('receipt_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_education',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('resume_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_experience',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('resume_id', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_business_documents_content_hash', table_name='business_documents')
    op.drop_index('ix_business_documents_document_type', table_name='business_documents')
    op.drop_index('ix_business_documents_status', table_name='business_documents')
    op.drop_table('business_documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_documents',
    sa.Column('id', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('stored_filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('document_type', postgresql.ENUM('INVOICE', 'RECEIPT', 'PURCHASE_ORDER', 'RESUME', 'EXPENSE_REPORT', 'APPLICATION_FORM', 'CONTRACT', 'UNKNOWN', name='businessdocumenttype'), autoincrement=False, nullable=False),
    sa.Column('type_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('requested_document_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'NEEDS_REVIEW', 'FAILED', name='businessdocumentstatus'), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extracted_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('field_confidence', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('validation_errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('missing_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('reviewed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='business_documents_pkey')
    )
    op.create_index('ix_business_documents_status', 'business_documents', ['status'], unique=False)
    op.create_index('ix_business_documents_document_type', 'business_documents', ['document_type'], unique=False)
    op.create_index('ix_business_documents_content_hash', 'business_documents', ['content_hash'], unique=False)
    op.drop_table('resume_experience')
    op.drop_table('resume_education')
    op.drop_table('receipt_items')
    op.drop_table('purchase_order_line_items')
    op.drop_table('invoice_line_items')
    op.drop_table('expense_report_items')
    op.drop_table('contract_signatories')
    op.drop_table('resumes')
    op.drop_table('receipts')
    op.drop_table('purchase_orders')
    op.drop_table('invoices')
    op.drop_table('expense_reports')
    op.drop_table('contracts')
    op.drop_table('application_forms')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_business_document_uploads_status'), table_name='business_document_uploads')
    op.drop_index(op.f('ix_business_document_uploads_document_type'), table_name='business_document_uploads')
    op.drop_index(op.f('ix_business_document_uploads_content_hash'), table_name='business_document_uploads')
    op.drop_table('business_document_uploads')
    # ### end Alembic commands ###
