"""business doc

Revision ID: 62d8b09cd61e
Revises: 65c81363ab75
Create Date: 2026-09-14 17:14:29.863470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d8b09cd61e'
down_revision: Union[str, None] = '65c81363ab75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_documents',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.Enum('INVOICE', 'RECEIPT', 'PURCHASE_ORDER', 'RESUME', 'EXPENSE_REPORT', 'APPLICATION_FORM', 'CONTRACT', 'UNKNOWN', name='businessdocumenttype'), nullable=False),
    sa.Column('type_confidence', sa.Float(), nullable=True),
    sa.Column('requested_document_type', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'NEEDS_REVIEW', 'FAILED', name='businessdocumentstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('field_confidence', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('missing_fields', sa.JSON(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_documents_content_hash'), 'business_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_business_documents_document_type'), 'business_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_business_documents_status'), 'business_documents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_documents_status'), table_name='business_documents')
    op.drop_index(op.f('ix_business_documents_document_type'), table_name='business_documents')
    op.drop_index(op.f('ix_business_documents_content_hash'), table_name='business_documents')
    op.drop_table('business_documents')
    # ### end Alembic commands ###
