"""ticket

Revision ID: a66cbc205651
Revises: 7875852c6d79
Create Date: 2026-08-28 14:30:18.722274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66cbc205651'
down_revision: Union[str, None] = '7875852c6d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('chat_sessions', sa.Column('ticket_number', sa.String(length=20), nullable=True))
    op.add_column('chat_sessions', sa.Column('hidden_from_customer', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_chat_sessions_ticket_number'), 'chat_sessions', ['ticket_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_ticket_number'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'hidden_from_customer')
    op.drop_column('chat_sessions', 'ticket_number')
    op.drop_column('chat_sessions', 'resolved_at')
    # ### end Alembic commands ###
