"""Policy/faq Migrate

Revision ID: b45bab330ebc
Revises: c5e47ec76b61
Create Date: 2026-08-27 10:42:41.593925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45bab330ebc'
down_revision: Union[str, None] = 'c5e47ec76b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
