"""Bargein

Revision ID: e877e8567ad6
Revises: ea36d4ff536e
Create Date: 2026-09-04 10:36:32.727960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e877e8567ad6'
down_revision: Union[str, None] = 'ea36d4ff536e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_config', sa.Column('barge_in_enabled', sa.Boolean(), nullable=False, server_default=sa.false(),))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot_config', 'barge_in_enabled')
    # ### end Alembic commands ###
