"""Voice Model

Revision ID: ea36d4ff536e
Revises: 701843f3cf0e
Create Date: 2026-09-02 18:02:33.308365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea36d4ff536e'
down_revision: Union[str, None] = '701843f3cf0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('channel', sa.String(length=10), nullable=False))
    op.add_column('chat_messages', sa.Column('message_type', sa.String(length=20), nullable=False))
    op.add_column('chat_sessions', sa.Column('channel', sa.String(length=10), nullable=False))
    op.add_column('chat_sessions', sa.Column('voice_session_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_chat_sessions_voice_session_id'), 'chat_sessions', ['voice_session_id'], unique=False)
    op.add_column('chatbot_config', sa.Column('voice_enabled', sa.Boolean(), nullable=False))
    op.add_column('chatbot_config', sa.Column('voice_name', sa.String(length=60), nullable=False))
    op.add_column('chatbot_config', sa.Column('voice_greeting_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot_config', 'voice_greeting_message')
    op.drop_column('chatbot_config', 'voice_name')
    op.drop_column('chatbot_config', 'voice_enabled')
    op.drop_index(op.f('ix_chat_sessions_voice_session_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'voice_session_id')
    op.drop_column('chat_sessions', 'channel')
    op.drop_column('chat_messages', 'message_type')
    op.drop_column('chat_messages', 'channel')
    # ### end Alembic commands ###
